### ISSUE TITLE
Could we have an update?

### ISSUE THREAD

**Issue by mname1150** [Animus565/ProdMafia#2]
Hey, could we get an update to this client? The previous discord link is expired. Thanks

**Comment by Animus565** [comment]
it got deleted

**Comment by mname1150** [comment]
Are there plans to bring it back, or is the project being discontinued? I enjoyed having a place we could gather and communicate.

**Comment by Animus565** [comment]
no plans

**Comment by mname1150** [comment]
Could we at least have a way to access our vaults? This client caused the exalt version to crash upon entering the vault.

**Comment by Animus565** [comment]
https://cdn.discordapp.com/attachments/876710343076900885/878742280918429746/g4pf0j.zip 2.0.0.3.0

**Comment by mname1150** [comment]
Sorry but... new update again. I've tried extracting the swf and updating manually but to no avail. Could we get another update for 2.0.1.0.0?

**Comment by Animus565** [comment]
Flash is discontinued as of the end of 2020. please stop using this client as it will no longer work. thank you for your patience 😃

**Comment by mname1150** [comment]
Haha, I see how it is. Regardless, thanks for all the updates and good luck!
